export interface Books {
  id: number,
  title: string,
  description: string,
  image: string,
  price: number,
}
const techBooks:Books[] = [
  {
    id: 1,
    title: "Chocolatecake",
    description: "Indulge in our rich and decadent Chocolate Cake, a heavenly treat that melts in your mouth with every bite!",
    image: "/images/1.jpg",
    price: 29.99,
  },
  {
    id: 2,
    title: "Customize Cherry cake",
    description: "Delight in our Customize Cherry Cake, where you can choose your favorite flavors and toppings to create a personalized cherry-infused masterpiece!.",
    image: "/images/2.jpg",
    price: 34.99,
  },
  {
    id: 3,
    title: "Mix Cake bars",
    description: "Savor our Mix Cake Bars, a delightful medley of flavors in every bite, perfect for satisfying your sweet tooth on the go!",
    image: "/images/3.jpg",
    price: 39.99,
  },
  {
    id: 4,
    title: "Birthday Cake",
    description: "Celebrate your special day with our Birthday Cake, a deliciously moist and beautifully decorated treat that brings joy to every celebration!",
    image: "/images/4.jpg",
    price: 42.99,
  },
  {
    id: 5,
    title: "LightPink Cake",
    description: "Delight in our Light Pink Cake, a soft and fluffy dessert adorned with delicate pastel hues, perfect for any sweet occasion!.",
    image: "/images/5.jpg",
    price: 45.99,
  },
  {
    id: 6,
    title: "Rounded Chocolate Cake",
    description: "Indulge in our Rounded Chocolate Cake, a rich and velvety treat with a smooth chocolate ganache, designed to satisfy every chocolate lover's craving",
    image: "/images/6.jpg",
    price: 39.99,
  },
  {
    id: 8,
    title: "Slice Cake",
    description: "Enjoy our Slice Cake, a perfectly portioned delight with layers of fluffy sponge and luscious frosting, ideal for any occasion",
    image: "/images/7.jpg",
    price: 55.99,
  },
  {
    id: 7,
    title: "Plum Cake",
    description: "Indulge in our Plum Cake, a moist and rich treat packed with dried fruits and aromatic spices, perfect for festive celebrations!",
    image: "/images/8.jpg",
    price: 49.99,
  },
  {
    id: 9,
    title: "Chocolate Tower Cake",
    description: "Experience the ultimate indulgence with our Chocolate Tower Cake, a decadent multi-layered delight overflowing with rich chocolate ganache and silky smooth frosting!.",
    image: "/images/9.jpg",
    price: 47.99,
  },
  {
    id: 10,
    title: "The Mythical Cake",
    description: "Unleash your imagination with The Mythical Cake, a whimsical creation adorned with vibrant colors and enchanting flavors, perfect for any magical celebration!",
    image: "/images/10.jpg",
    price: 32.99,
  },
  {
    id: 11,
    title: "The Classical Cake",
    description: "Indulge in The Classical Cake, a timeless masterpiece featuring rich layers of moist sponge and velvety frosting, embodying the elegance of traditional baking.",
    image: "/images/11.jpg",
    price: 37.99,
  },
  {
    id: 12,
    title: "Sista Cake",
    description: "Sista Cake is a delightful fusion of flavors, combining soft layers of cake with creamy filling and a touch of nostalgia, perfect for sharing with loved ones.",
    image: "/images/12.jpg",
    price: 31.99,
  },
  {
    id: 13,
    title: "Strawberry Sprinkle Cake",
    description: "Strawberry Sprinkle Cake is a vibrant treat, featuring fluffy layers infused with fresh strawberries, adorned with colorful sprinkles for a fun and festive finish.",
    image: "/images/13.jpg",
    price: 39.99,
  },
  {
    id: 14,
    title: "Rounded Strawberry Cake",
    description: "Rounded Strawberry Cake is a delightful creation, featuring soft, rounded layers filled with luscious strawberry cream, topped with fresh strawberries and a light, creamy frosting for a refreshing taste.",
    image: "/images/14.jpg",
    price: 44.99,
  },
  {
    id: 15,
    title: "White Creamy Cremelo",
    description: "White Creamy Cremelo is a luxurious dessert that boasts layers of velvety white cream and rich chocolate, creating a heavenly combination that's both light and indulgent. Perfect for any celebration!",
    image: "/images/15.jpg",
    price: 52.99,
  },
];

export default techBooks;
